server:
  port: ${PORT:9000}

spring:
  application:
    name: gateway-service

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    user-service:
      sensitiveHeaders:
      path: /user/**
      serviceId: user-service
      strip-prefix: true
    item-service:
      sensitiveHeaders:
      path: /item/**
      serviceId: item-service
      strip-prefix: true
